### ISSUE TITLE
HPCE-2015-v2 AMI

### ISSUE THREAD

**Issue by dantarakan** [HPCE/hpce-2015-cw5#7]
@m8pple , where can we find the HPCE-2015-v2 AMI? This would be useful to check that everything builds correctly.

**Comment by m8pple** [comment]
When launching an AWS instance:
- choose the "US East (North Virginia)" zone (usually the cheapest)
- select from publically available AMIs
- search for "HPCE".

**Comment by dantarakan** [comment]
@m8pple , thanks!
